--LAB-8 CURSOR,FUNCTION,PROCEDURE


--CURSOR

SET SERVEROUTPUT ON
DECLARE
     CURSOR CUST_CUR IS
  SELECT NAME,ADDRESS,PHONE FROM CUSTOMER10;
  RECORD CUST_CUR%ROWTYPE;

BEGIN

OPEN CUST_CUR;
     
      LOOP
        FETCH CUST_CUR INTO RECORD;
        EXIT WHEN CUST_CUR%ROWCOUNT >3;
      DBMS_OUTPUT.PUT_LINE ('NAME : ' || RECORD.NAME || ' ADDRESS : ' || RECORD.ADDRESS || ' PHONE NO-' || RECORD.PHONE);
	  END LOOP;
      CLOSE CUST_CUR;   
END;
/

-- FUNCTIONS

SET SERVEROUTPUT ON
CREATE OR REPLACE FUNCTION GET_OWNER(HOUSE_NO HOME_POLICY.H_NO%TYPE) RETURN VARCHAR IS
NAME HOME_POLICY.OWNER_NAME%TYPE;

BEGIN

SELECT OWNER_NAME INTO NAME FROM HOME_POLICY WHERE HOME_POLICY.H_NO=HOUSE_NO;
RETURN NAME;
END;
/

SET SERVEROUTPUT ON
DECLARE
HOUSE_NO HOME_POLICY.H_NO%TYPE;
BEGIN
HOUSE_NO:=&HOUSE_NO;
DBMS_OUTPUT.PUT_LINE('OWNER NAME OF THIS HOUSE'|| GET_OWNER(HOUSE_NO) );
END;
/

--PROCEDURE TO COUNT TIME
SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE TIME_COUNT(POLD AUTO_POLICY.POL_NO%TYPE) IS 
PRC AUTO_POLICY.ISSUE_DATE%TYPE;
V_DATE1 DATE := SYSDATE;


DIFF INTEGER;

BEGIN
  
  SELECT ISSUE_DATE INTO PRC FROM AUTO_POLICY
 WHERE POL_NO=POLD;
  
    DIFF    := (V_DATE1 - PRC);
       DBMS_OUTPUT.PUT_LINE('DIFF  : ' || DIFF ||' DAYS');
	IF(DIFF>3600)
	THEN
	    DBMS_OUTPUT.PUT_LINE('RENEW YOUR POLICY,TIME IS OVER'); 
END IF;
END;
/

BEGIN
TIME_COUNT(5571);
END;
/


--PROCEDURE TO MATCH COVERAGE AND PRICE


CREATE OR REPLACE PROCEDURE MATCH_PRICE(POLICID POLICY.P_NO%TYPE) IS 
PRC POLICY.COVERAGE%TYPE;
PTC POLICY.TERM_PRICE%TYPE;

BEGIN
SELECT COVERAGE INTO PRC FROM POLICY
WHERE P_NO=POLICID;

SELECT TERM_PRICE INTO PTC FROM POLICY
WHERE P_NO=POLICID;

PRC:=PRC+PTC;
UPDATE POLICY SET COVERAGE=PRC WHERE
P_NO=POLICID;
COMMIT;
END MATCH_PRICE;
/
SELECT *FROM POLICY;
